webapp/ads/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SelectMultipleField, widgets, BooleanField


class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class FilterForm(FlaskForm):
    price_min = IntegerField('price_min', render_kw={'class': 'form-control'})
    price_max = IntegerField('price_max', render_kw={'class': 'form-control'})
    rooms = [(0, 'Студия'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]
    rooms = MultiCheckboxField('rooms', choices=rooms, coerce=int, render_kw={'class': 'form-check-input'})
    area_min = IntegerField('area_min', render_kw={'class': 'form-control'})
    area_max = IntegerField('area_max', render_kw={'class': 'form-control'})
    type_material = [("Кирпичный", 'Кирпичный'), ("Монолитный", 'Монолитный'), ("Панельный", 'Панельный')]
    material = MultiCheckboxField('material', choices=type_material, coerce=str)
    commission = BooleanField('Без коммиссии', render_kw={'class': 'form-check-input'})
    deposit = BooleanField('Без залога', render_kw={'class': 'form-check-input'})

webapp/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_login import LoginManager
from webapp.model import db, User
from webapp.ads.veiws import blueprint as ads_blueprint
from webapp.user.views import blueprint as user_blueprint


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    app.register_blueprint(ads_blueprint)
    app.register_blueprint(user_blueprint)
    migrate = Migrate(app, db)
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'login'

    @login_manager.user_loader
    def user_load(user_id):
        return User.query.get(user_id)
    return app

webapp/user/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required
from webapp.user.form import LoginForm
from webapp.model import User


blueprint = Blueprint('user', __name__)


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('ads.index'))
    form = LoginForm()
    return render_template('user/login.html', form=form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Вы вошли на сайт')
            return redirect(url_for('ads.index'))
    flash('Неверное имя пользователя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('ads.index'))

webapp/templates/index.html
{% extends 'Base.html' %}
{% block content %}>
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}
<div class="container-sm">
  <h4>Аренда квартир в Москве</h4><br>
  <div class="h-100 p-5 bg-light border rounded-3">
    <form action="{{ url_for('ads.result') }}" method="POST">
      <div class='row '>
        <div class='col-4'>
          <div class="input-group input-group-sm mb-3">
            <span class="input-group-text">Цена</span>
            {{ form.hidden_tag() }}
            {{ form.price_min(type='number', placeholder="От") }}
            {{ form.price_max(type='number', placeholder="До") }}
          </div>
          
          <h7>Количество комнат:</h7><br><br>
          {% for i in form.rooms %}
            {{ i }}
            {{ i.label }}<br>
          {% endfor %}<br>
        </div>
      
        <div class='col-4'>
          <div class="input-group input-group-sm mb-3">
            <span class="input-group-text">Площаль</span>
              {{ form.area_min(type='number', placeholder="От")}}
              {{ form.area_max(type='number', placeholder="До") }}
          </div>
          <h7>Тип дома:</h7><br><br>
          {% for i in form.material %}
            {{ i }}
            {{ i.label }}<br>
          {% endfor %}<br>
          <div class="form-check">
            {{ form.commission() }} {{ form.commission.label }}<br>
            {{ form.deposit() }} {{ form.deposit.label }}<br>
          </div>
        </div>
      </div>
      <input type="submit" value="Применить фильтр">
    </form>
  </div>
</div><br><br>
          
<div class="container-sm">
  <div class="col-8">
    <h5>Результаты запроса:</h5><br>
    {% for flat in flats.items %}
      <div class="h-100 p-5 bg-light border rounded-3">
        <div class="container-sm">
          <div class="row">
            <div class="col">
              <a href={{ flat.link }} target="_blank">{{ flat.num_rooms }}-комнатная квартира {{ flat.area}} м²</a><br>
              <h7>{{ flat.street }}</h7><br>
              <h7>м. {{ flat.metro }}</h7>
            </div>
            <div class="col-4">
              <h7>{{ flat.price }} &#8381/мес.</h7><br>
              {% if flat.deposit == 0 %}
                <h7>Без залога</h7><br>
              {% else %}
                <h7>Залог {{ flat.deposit }} &#8381</h7><br>
              {% endif %}
              {% if flat.commission == 0 %}
                <h7>Без комиссии</h7><br>
              {% else %}
                <h7>Комиссия {{ flat.commission }} %</h7><br>
              {% endif %}
              <h1></h1>
              <a href={{ flat.link }} button type="button" target="_blank" class="btn btn-primary btn-sm">Перейти к объявлению</a><br>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}<br>
    <nav aria-label="...">
      <ul class="pagination">
        <li class="page-item {% if not flats.has_prev %} disabled {% endif %}">
          <a class="page-link" href="http://127.0.0.1:5000/{{ url_for(request.endpoint) }}?page={{ flats.prev_num }}">Назад</a>
        </li>
    
        {% for flat in flats.iter_pages() %}
          {% if flat %}
            <li class="page-item {% if flat == flats.page %} active {% endif %}">
              <a class="page-link" href="http://127.0.0.1:5000/{{ url_for(request.endpoint) }}?page={{ flat }}">{{ flat }}</a>
            </li>
          {% endif %}
        {% endfor %}
        
        <li class="page-item {% if not flats.has_next %} disabled {% endif %}">
          <a class="page-link" href="http://127.0.0.1:5000/{{ url_for(request.endpoint) }}?page={{ flats.next_num }}">Вперед</a>
        </li>
      </ul>
    </nav>
  </div>
</div>

{% endblock %}

webapp/templates/user/login.html
{% extends 'base.html' %}
{% block content %}
<div class='col-4'>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <form action={{ url_for('user.process_login') }} method="POST">
        {{ form.hidden_tag() }}
        {{ form.username.label }}<br>
        {{ form.username() }}<br>

        {{ form.password.label }}<br>
        {{ form.password() }}<br>
        {{ form.submit() }}
    </form>
</div>
{% endblock %}